POST http://localhost:5005/webhooks/rest/webhook  HTTP/1.1
content-type: application/json

{
  "sender": "demo",
  "message": "hello"
}
###

POST  http://localhost:5005/model/parse HTTP/1.1
content-type: application/json

{
  "text": "I need a table for tomorrow. I will be comming with 13 people"
}

###


POST http://localhost:3000/nlp/communicate  HTTP/1.1
content-type: application/json

{
  "message": "need a table for 3 tomorrow"

}